Server:
  Port: 22000

Lark:
  AppID: cli_a5c372574e18100b
  AppSecret : xxxxxxxxxxxxxxxxxxx
  EncryptKey: xxxxxxxxxxxxxxxxxxx
  VerificationToken: xxxxxxxxxxxxxxxxxxx
  UpdateTokenDeltaTimeSecond: 10
