tenant_access_token: 
    name : "tenant_access_token"
    url : "https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal"
    method : "POST"

app_access_token: 
    name : "app_access_token"
    url : "https://open.feishu.cn/open-apis/auth/v3/app_access_token/internal"
    method : "POST"

messages: 
    name : "messages"
    url : "https://open.feishu.cn/open-apis/im/v1/messages"
    method : "POST"
